### PR TITLE
Add static target

### PR DESCRIPTION
**Pull request by subdiff**
Builds a static version of the lib which allows static linking against it.

### CODE REVIEW

**Comment by emersion** [comment]
You should already be able to do this by `-Ddefault_library=static` (or `both`). Or am I missing anything?

**Comment by subdiff** [comment]
> You should already be able to do this by providing `-Ddefault_library=static` to Meson (or `both`). Or am I missing anything?

Yea, I guess you're right, I'm not a Meson expert. I didn't notice that the code I based this approach on was actually added later on to a fork of wlroots: https://github.com/Plagman/wlroots/commit/cccd0a099d6dacd2c86e29a977eabf716ada4699

You know if there is a way to do this subproject-thing without changing the meson.build file but for example with -Ddefault_library=static?

**Comment by emersion** [comment]
>You know if there is a way to do this subproject-thing without changing the meson.build file but for example with -Ddefault_library=static?

You should be able to set `default_library` in `default_options` when using `subproject()`: https://mesonbuild.com/Reference-manual.html#subproject

Something like this should do it:

```meson
libliftoff = subproject('libliftoff',
    'default_options': ['default_library=static'],
)
```

**Comment by subdiff** [comment]
> > You know if there is a way to do this subproject-thing without changing the meson.build file but for example with -Ddefault_library=static?
> 
> You should be able to set `default_library` in `default_options` when using `subproject()`: https://mesonbuild.com/Reference-manual.html#subproject
> 
> Something like this should do it:
> 
> ```meson
> libliftoff = subproject('libliftoff',
>     'default_options': ['default_library=static'],
> )
> ```

I tried this but it doesn't seem to work. Also wouldn't the issue be that the other set default_options become unset by that?

In any case there is probably another solution and the one this MR presents here is not the one that should go upstream since it's uncommon after all. I'll close the MR because of that.

**Comment by emersion** [comment]
>I tried this but it doesn't seem to work.

If you start with a clean build dir, what ends up being built in there? The dynamic library?

>Also wouldn't the issue be that the other set default_options become unset by that?

Hmm, which other default_options?

>In any case there is probably another solution and the one this MR presents here is not the one that should go upstream since it's uncommon after all. 

Agreed.

**Comment by emersion** [comment]
https://mesonbuild.com/Release-notes-for-0-54-0.html#per-subproject-default_library-and-werror-options

**Pull request closed without merging**
